<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\YMM4CloudSync.YMMX.Core\YMM4CloudSync.YMMX.Core.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Version>0.1.7</Version>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>

    <SelfContained>false</SelfContained>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>

    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

    <OutDir>$(SolutionDir)build\$(Configuration)\</OutDir>
    <ApplicationIcon>Resources\YMMX_logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\YMMX_logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
