name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    name: Build and Release
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.x"

      - name: Create Google Drive Credentials
        run: |
          $template = Get-Content "YMM4CloudSync.Core/Services/GoogleDriveCredentials.cs.example" -Raw
          $content = $template -replace 'PLACEHOLDER_CLIENT_ID', '${{ secrets.GOOGLE_CLIENT_ID }}'
          $content = $content -replace 'PLACEHOLDER_CLIENT_SECRET', '${{ secrets.GOOGLE_CLIENT_SECRET }}'
          Set-Content "YMM4CloudSync.Core/Services/GoogleDriveCredentials.cs" $content

      - name: Create OneDrive Credentials
        run: |
          $template = Get-Content "YMM4CloudSync.Core/Services/OneDriveCredentials.cs.example" -Raw
          $content = $template -replace 'PLACEHOLDER_CLIENT_ID', '${{ secrets.ONEDRIVE_CLIENT_ID }}'
          Set-Content "YMM4CloudSync.Core/Services/OneDriveCredentials.cs" $content

      - name: Create OneDrive Credentials
        run: |
          $template = Get-Content "YMM4CloudSync.Core/Services/DropboxCredentials.cs.example" -Raw
          $content = $template -replace 'PLACEHOLDER_CLIENT_ID', '${{ secrets.DROPBOX_CLIENT_ID }}'
          $content = $content -replace 'PLACEHOLDER_CLIENT_SECRET', '${{ secrets.DROPBOX_CLIENT_SECRET }}'
          Set-Content "YMM4CloudSync.Core/Services/DropboxCredentials.cs" $content

      - name: Publish
        run: dotnet publish --configuration Release -o publish

      - name: Copy README to publish folder
        run: Copy-Item ".github\assets\readme.txt" -Destination "publish\readme.txt"

      - name: Create ZIP
        run: Compress-Archive -Path "publish\*" -DestinationPath "publish\YMM4CloudSync.zip"

      - name: Rename ZIP to .ymme
        run: Move-Item publish\YMM4CloudSync.zip publish\YMM4CloudSync.ymme

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: publish/YMM4CloudSync.ymme
          draft: true
          prerelease: true
